/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-07 01:56:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Sign up</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"style/general_ui.css\">    \n");
      out.write("    <link rel=\"stylesheet\" href=\"style/signup.css\">    \n");
      out.write("    <script src=\"script/jquery-git.min.js\"></script>\n");
      out.write("    <script src=\"script/signup.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"background-style\">\n");
      out.write("<div class=\"auth-box\">\n");
      out.write("    <div class=\"page-title\" style=\"margin-top:20px;\">\n");
      out.write("        Sign up your account\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <div class=\"text-input\">\n");
      out.write("        <label for=\"email\" class=\"text-input-box-label\">Email</label>\n");
      out.write("        <input type=\"text\" placeholder=\"example@gmail.com\" id=\"email\" class=\"text-input-box\"/>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-box-item\">\n");
      out.write("        <label for=\"gender\" class=\"text-input-box-label\">gender</label>  \n");
      out.write("        <div id=\"gender\">\n");
      out.write("            <label for=\"male\" class=\"text-input-box-label\" style=\"padding-left:40px;width:20px;\">Male</label>\n");
      out.write("            <input type=\"radio\"  checked='checked' id=\"male\" name=\"gender\" value=\"1\"/>  \n");
      out.write("            <label for=\"female\" class=\"text-input-box-label\" style=\"padding-left:80px;width:20px;\">Female</label>\n");
      out.write("            <input type=\"radio\" id=\"female\" name=\"gender\" value=\"0\"/>  \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"text-input\">\n");
      out.write("        <label for=\"age\" class=\"text-input-box-label\">Age</label>\n");
      out.write("        <input type=\"text\" name=\"age\" pattern=\"[0-9]\"  placeholder=\"18\"  id=\"age\" class=\"text-input-box\"/>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"text-input\">\n");
      out.write("        <label for=\"password\" class=\"text-input-box-label\">Password</label>\n");
      out.write("        <input type=\"password\" placeholder=\"********\" id=\"password\" class=\"text-input-box\"/>\n");
      out.write("    </div>\n");
      out.write("    <!--\n");
      out.write("    \n");
      out.write("    <div class=\"text-input\">\n");
      out.write("        <label for=\"password\" class=\"text-input-box-label\">Retype Password</label>\n");
      out.write("        <input type=\"password\"   placeholder=\"********\" id=\"password\" class=\"text-input-box\"/>\n");
      out.write("    </div> -->\n");
      out.write("    <button class=\"button\" id=\"signup-button\">\n");
      out.write("        Sign up\n");
      out.write("    </button>\n");
      out.write("   \n");
      out.write("    <div class=\"auth-box-item\" style=\"margin-bottom:30px;margin-top:20px;\">\n");
      out.write("        Have an account <a href=\"/eorm/login\" class=\"link-text\">Login</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
